stages:
- name: Build
  steps:
  - runScriptConfig:
      image: maven:3-openjdk-11
      shellScript: mvn package -DskipTests
- name: Build Docker with DIND
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: docker.dev.folio.org/mod-bulk-edit:firebird-latest
      pushRemote: true
      registry: docker.dev.folio.org
- name: Deploy
  steps:
  - applyAppConfig:
      catalogTemplate: p-ngvqv:firebird-helmcharts-mod-bulk-edit
      version: 0.1.30
      answers:
        image.repository: docker.dev.folio.org/mod-bulk-edit
        image.tag: firebird-latest
        postJob.enabled: true
      targetNamespace: firebird
      name: mod-bulk-edit
timeout: 60
notification: {}
