spring:
  cache:
    type: none
  application:
    name: @project.artifactId@
    version: @project.version@
  datasource:
    continue-on-error: true
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_DATABASE:okapi_modules}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml

management:
  endpoints:
    web:
      base-path: /admin
    health:
      defaults:
        enabled: false
      readinessstate:
        enabled: true

logging:
  level:
    org:
      springframework:
        cache: OFF

server.port: 8081
folio.tenant.validation.enabled: false
